
Albedo=double(netcdf.getVar(netcdf.open('sAlbedo.nc','NC_NOWRITE'),0));
NDVI=double(netcdf.getVar(netcdf.open('sNDVI.nc','NC_NOWRITE'),0));
SWd24=double(netcdf.getVar(netcdf.open('sSWd24.nc','NC_NOWRITE'),0));
Uref=double(netcdf.getVar(netcdf.open('sUref.nc','NC_NOWRITE'),0));
lat=double(netcdf.getVar(netcdf.open('slat.nc','NC_NOWRITE'),0))*180.0/pi;
Emissivity=double(netcdf.getVar(netcdf.open('sEmissivity.nc','NC_NOWRITE'),0));
Ns=double(netcdf.getVar(netcdf.open('sNs.nc','NC_NOWRITE'),0));
Ta_avg=double(netcdf.getVar(netcdf.open('sTa_avg.nc','NC_NOWRITE'),0));
fc=double(netcdf.getVar(netcdf.open('sfc.nc','NC_NOWRITE'),0));
lon=double(netcdf.getVar(netcdf.open('slon.nc','NC_NOWRITE'),0))*180.0/pi;
LAI=double(netcdf.getVar(netcdf.open('sLAI.nc','NC_NOWRITE'),0));
Pressure=double(netcdf.getVar(netcdf.open('sPressure.nc','NC_NOWRITE'),0));
Ta_ref=double(netcdf.getVar(netcdf.open('sTa_ref.nc','NC_NOWRITE'),0));
hc=double(netcdf.getVar(netcdf.open('shc.nc','NC_NOWRITE'),0));
prmsl=double(netcdf.getVar(netcdf.open('sprmsl.nc','NC_NOWRITE'),0));
LWd=double(netcdf.getVar(netcdf.open('sLWd.nc','NC_NOWRITE'),0));
SWd=double(netcdf.getVar(netcdf.open('sSWd.nc','NC_NOWRITE'),0));
Ts=double(netcdf.getVar(netcdf.open('sTs.nc','NC_NOWRITE'),0));
hpbl=double(netcdf.getVar(netcdf.open('shpbl.nc','NC_NOWRITE'),0));
qa_ref=double(netcdf.getVar(netcdf.open('sqa_ref.nc','NC_NOWRITE'),0));
LSM=double(netcdf.getVar(netcdf.open('sLSM.nc','NC_NOWRITE'),0));
sComptMask=double(netcdf.getVar(netcdf.open('sComptMask.nc','NC_NOWRITE'),0));

saveas(Graph(Albedo,lat,lon,'Albedo-V04H09-2008-194-ECMWF'),'Albedo.png');close
saveas(Graph(NDVI,lat,lon,'NDVI-V04H09-2008-194-ECMWF'),'NDVI.png');close
saveas(Graph(SWd24,lat,lon,'SWd24-V04H09-2008-194-ECMWF'),'SWd24.png');close
saveas(Graph(Uref,lat,lon,'Uref-V04H09-2008-194-ECMWF'),'Uref.png');close
saveas(Graph(Emissivity,lat,lon,'Emissivity-V04H09-2008-194-ECMWF'),'Emissivity.png');close
saveas(Graph(Ns,lat,lon,'Ns-V04H09-2008-194-ECMWF'),'Ns.png');close
saveas(Graph(Ta_avg,lat,lon,'Ta_avg-V04H09-2008-194-ECMWF'),'Ta_avg.png');close
saveas(Graph(fc,lat,lon,'fc-V04H09-2008-194-ECMWF'),'fc.png');close
saveas(Graph(LAI,lat,lon,'LAI-V04H09-2008-194-ECMWF'),'LAI.png');close
saveas(Graph(Pressure,lat,lon,'Pressure-V04H09-2008-194-ECMWF'),'Pressure.png');close
saveas(Graph(Ta_ref,lat,lon,'Taref-V04H09-2008-194-ECMWF'),'Ta_ref.png');close
saveas(Graph(hc,lat,lon,'hc-V04H09-2008-194-ECMWF'),'hc.png');close
saveas(Graph(prmsl,lat,lon,'prmsl-V04H09-2008-194-ECMWF'),'prmsl.png');close
saveas(Graph(LWd,lat,lon,'LWd-V04H09-2008-194-ECMWF'),'LWd.png');close
saveas(Graph(SWd,lat,lon,'SWd-V04H09-2008-194-ECMWF'),'SWd.png');close
saveas(Graph(Ts,lat,lon,'Ts-V04H09-2008-194-ECMWF'),'Ts.png');close
saveas(Graph(hpbl,lat,lon,'hpbl-V04H09-2008-194-ECMWF'),'hpbl.png');close
saveas(Graph(qa_ref,lat,lon,'qaref-V04H09-2008-194-ECMWF'),'qa_ref.png');close
saveas(Graph(LSM,lat,lon,'LSM-V04H09-2008-194-ECMWF'),'LSM.png');close
saveas(Graph(sComptMask,lat,lon,'sComptMask-V04H09-2008-194-ECMWF'),'sComptMask.png');close
